### ISSUE TITLE
CSRF support

### ISSUE THREAD

**Issue by Mte90** [volfpeter/fasthx#38]
I am trying to implement a login and taking inspiration from https://github.com/Hybridhash/FastAPI-HTMX/blob/main/app/routes/view/login.py that uses https://pypi.org/project/fastapi-csrf-protect/

The issue is that a code like this doesn't work:

```
    @jinja.hx("login.html")
    @app.get(
        "/login",
        summary="Gets the login page",
        tags=["Pages", "Authentication"],
    )
    async def get_login(
        request: Request,
        csrf_protect: CsrfProtect = Depends(),
    ):
        csrf_token, signed_token = csrf_protect.generate_csrf_tokens()
        context = {
            "request": request,
            "csrf_token": csrf_token,
        }

        csrf_protect.set_csrf_cookie(signed_token,'')
        return context
```

The `set_csrf_cookie` need the response but with this package there is any response.

**Comment by volfpeter** [comment]
Hi,

There are quite a few issues in your code snippet.

One fundamental bug is that  `@jinja.hx` must be applied "first" (directly on your route implementation), and `@app.get()` must always be your outermost decorator. Whatever you have "outside" of `app.get()` will not be executed by FastAPI because it can not know about it.

The second issue is that you should never add `request` to the rendering context manually - it is done automatically by `fasthx`.

The third thing is that you should have `csrf_protect.generate_csrf_tokens()` in a separate dependency that sets the cookie on the response (you can have `response: Response` dependencies in routes or dependencies) and returns the token that can be used in forms. This is important because this way token generation would only happen once and you could use that in any dependency that you'll have in the future.

With all that done, you can replace the default Jinja rendering context factory with one that includes (at least some of) your route's dependencies in the rendering context. See the `Jinja.make_context` [docs here](https://volfpeter.github.io/fasthx/api/jinja/#fasthx.Jinja.make_context).

After all these changes, your route would be simplified to `def  login_page(csrf_token: str = Depends(get_csrf_token)) -> None: ...` and everything should work.

If you need this for a business project, I recommend contacting me for consulting to help you get started correctly. My contact info is on my profile page.

I hope I helped.

Peter

**Comment by Mte90** [comment]
Thanks for the iinformation, I have to see what I can do.
My plan was to do a better template for FastAPI with HTMX support and already a login system (and tailwind), so I started doing that mix.

I am from Django and there it is more simple to do a lot of things without mixing too many things.

**Comment by volfpeter** [comment]
Yeah, Django comes with everything and more, but on the other hand, it takes a ton of decisions out of your hand.

I hope my comments will help you get started with FastAPI and FastHX. I'll close the issue as I think the question is answered and I like to keep the issue tracker tidy. But of course feel free to continue this thread.
